use crate::{ProviderConfig, ProviderProtocol};
use std::collections::HashMap;

pub(crate) fn builtin_provider_config(name: &str) -> Option<ProviderConfig> {
    match name {
        "anthropic" => Some(ProviderConfig {
            protocol: ProviderProtocol::AnthropicMessages,
            tool_protocol: Default::default(),
            base_url: None,
            api_key: None,
            api_key_env: Some("ANTHROPIC_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "openai" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: None,
            api_key: None,
            api_key_env: Some("OPENAI_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "google" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://generativelanguage.googleapis.com/v1beta".to_string()),
            api_key: None,
            api_key_env: Some("GOOGLE_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "deepseek" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://api.deepseek.com".to_string()),
            api_key: None,
            api_key_env: Some("DEEPSEEK_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "qwen" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://dashscope.aliyuncs.com/compatible-mode/v1".to_string()),
            api_key: None,
            api_key_env: Some("DASHSCOPE_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "zhipu" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://open.bigmodel.cn/api/paas/v4".to_string()),
            api_key: None,
            api_key_env: Some("ZHIPU_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "zai" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://api.z.ai/api/paas/v4".to_string()),
            api_key: None,
            api_key_env: Some("ZAI_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "zhipu-coding-plan" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://open.bigmodel.cn/api/coding/paas/v4".to_string()),
            api_key: None,
            api_key_env: Some("ZHIPU_CODING_PLAN_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "zai-coding-plan" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://api.z.ai/api/coding/paas/v4".to_string()),
            api_key: None,
            api_key_env: Some("ZAI_CODING_PLAN_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "minimax" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://api.minimaxi.com/v1".to_string()),
            api_key: None,
            api_key_env: Some("MINIMAX_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "moonshot" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://api.moonshot.cn/v1".to_string()),
            api_key: None,
            api_key_env: Some("MOONSHOT_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        "openrouter" => Some(ProviderConfig {
            protocol: ProviderProtocol::OpenAIChat,
            tool_protocol: Default::default(),
            base_url: Some("https://openrouter.ai/api/v1".to_string()),
            api_key: None,
            api_key_env: Some("OPENROUTER_API_KEY".to_string()),
            models: HashMap::new(),
        }),
        _ => None,
    }
}
