//! Build script for talos-tools.
//!
//! Parses `src/bash_permission_policy.toml` at build time and generates a
//! static Rust source artefact under `OUT_DIR`.  The committed TOML is the
//! single source of truth.  Every required field must be present and every
//! array element must be a string — a malformed TOML fails the build.

use std::path::Path;

const REQUIRED_FIELDS: &[&str] = &[
    "read_only_programs",
    "read_only_no_arg_programs",
    "read_only_git_subcommands",
    "read_only_find_denied_args",
    "validation_cargo_subcommands",
    "validation_go_subcommands",
    "validation_programs",
];

fn main() {
    println!("cargo:rerun-if-changed=src/bash_permission_policy.toml");

    let toml_path = Path::new("src/bash_permission_policy.toml");
    let content =
        std::fs::read_to_string(toml_path).expect("bash_permission_policy.toml must exist");

    let root = content
        .parse::<toml::Table>()
        .expect("bash_permission_policy.toml must be valid TOML");

    // Strict schema validation: every required field must exist and be a
    // string array.  Silent filter_map / unwrap_or_default would mask a
    // malformed policy that the old toml::from_str<BashPermissionPolicy>
    // would have rejected.
    for &field in REQUIRED_FIELDS {
        let value = root.get(field).unwrap_or_else(|| {
            panic!("bash_permission_policy.toml: missing required field [{field}]")
        });

        let arr = value.as_array().unwrap_or_else(|| {
            panic!("bash_permission_policy.toml: [{field}] must be an array")
        });

        for (i, item) in arr.iter().enumerate() {
            let _ = item.as_str().unwrap_or_else(|| {
                panic!("bash_permission_policy.toml: [{field}][{i}] must be a string")
            });
        }
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set");
    let dest = Path::new(&out_dir).join("bash_permission_policy_data.rs");

    let code = generate_policy_rust(&root);
    std::fs::write(&dest, code).expect("failed to write generated policy");
}

/// Read a string-array field.  Caller has already validated the field exists
/// and every element is a string, so unwrap/collect is safe.
fn get_strs(root: &toml::Table, key: &str) -> Vec<String> {
    root.get(key)
        .and_then(|v| v.as_array())
        .map(|arr| arr.iter().filter_map(|v| v.as_str().map(String::from)).collect())
        .unwrap_or_default()
}

fn generate_policy_rust(root: &toml::Table) -> String {
    let mut s = String::with_capacity(2048);
    s.push_str("// Auto-generated by build.rs from src/bash_permission_policy.toml.\n");
    s.push_str("// Do not edit manually.\n\n");
    s.push_str("BashPermissionPolicy {\n");

    for &field in REQUIRED_FIELDS {
        let values = get_strs(root, field);
        s.push_str(&format!("    {field}: vec![\n"));
        for v in &values {
            s.push_str(&format!("        \"{}\".to_string(),\n", v.escape_debug()));
        }
        s.push_str("    ],\n");
    }

    s.push_str("}\n");
    s
}